[package]
name = "c64_binary_file_converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
fltk = {version = "^1.5.4", features = ["fltk-bundled"]}
quick-xml = { version = "0.37.2" }